# Generated by Django 2.0.1 on 2018-01-05 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anemoment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winddata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
